parameters:
  buildconfig: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Build code'
  inputs:
    command: build
    projects: '**/*.csproj'
    arguments: --no-restore --configuration ${{ parameters.buildconfig }}

- task: DotNetCoreCLI@2
  displayName: 'Publish the dotnet project'
  inputs:
    command: 'publish'
    projects: '**/*.csproj'
    arguments: '--no-build --configuration ${{ parameters.buildconfig }} --output $(Build.ArtifactStagingDirectory)/Release'
    ZipAfterPublish: true